import 'package:flutter/material.dart';

/// Lightweight app-wide strings for the four user-selectable UI languages.
/// Unlisted user content and food names stay exactly as entered.
class AppText extends StatelessWidget {
  const AppText(
    this.data, {
    super.key,
    this.style,
    this.strutStyle,
    this.textAlign,
    this.textDirection,
    this.locale,
    this.softWrap,
    this.overflow,
    this.maxLines,
    this.semanticsLabel,
    this.textWidthBasis,
    this.textHeightBehavior,
    this.selectionColor,
  });

  final String data;
  final TextStyle? style;
  final StrutStyle? strutStyle;
  final TextAlign? textAlign;
  final TextDirection? textDirection;
  final Locale? locale;
  final bool? softWrap;
  final TextOverflow? overflow;
  final int? maxLines;
  final String? semanticsLabel;
  final TextWidthBasis? textWidthBasis;
  final TextHeightBehavior? textHeightBehavior;
  final Color? selectionColor;

  static const _strings = <String, Map<String, String>>{
    'ja': {
      'Home': 'ホーム',
      'Calories over time': 'カロリーの推移',
      'A view of your logged food across the selected period.':
          '選択した期間の食事記録を表示します。',
      'Week': '週',
      'Month': '月',
      'Quarter': '四半期',
      'Year': '年',
      'TOTAL': '合計',
      'DAILY AVERAGE': '1日平均',
      'In this period': 'この期間',
      'Per day or month': '1日または1か月あたり',
      'Logged calories': '記録したカロリー',
      'Your trend starts with a meal': '食事を記録して推移を見ましょう',
      'Add food item': '食品を追加',
      'Today': '今日',
      'Diary': '日記',
      'Plan': '予定',
      'Progress': '進捗',
      'Settings': '設定',
      'Breakfast': '朝食',
      'Lunch': '昼食',
      'Dinner': '夕食',
      'Snack': '間食',
      'Log food': '食事を記録',
      'Add to this day': 'この日に追加',
      'Search': '検索',
      'Cancel': 'キャンセル',
      'Save': '保存',
      'Close': '閉じる',
      'Continue': '続ける',
      'Your name': 'お名前',
      'Shown in the app header': 'アプリのヘッダーに表示されます',
      'Country / food reference': '国・食品データ',
      'Language': '言語',
      'English': '英語',
      '日本語': '日本語',
      '中文': '中国語',
      '한국어': '韓国語',
      'Color theme': 'テーマ',
      'System': '端末の設定',
      'Light': 'ライト',
      'Dark': 'ダーク',
      'Following your device appearance': '端末の表示設定に合わせる',
      'PERSONALIZATION': 'パーソナライズ',
      'APPEARANCE': '外観',
      'PROFILE & GOAL': 'プロフィールと目標',
      'BACKUP & RESTORE': 'バックアップと復元',
      'PRIVACY': 'プライバシー',
      'FOOD DATA & PRIVACY': '食品データとプライバシー',
      'Body profile': '身体プロフィール',
      'Weight goal': '体重目標',
      'Privacy policy': 'プライバシーポリシー',
      'Export a backup': 'バックアップをエクスポート',
      'Import a backup': 'バックアップをインポート',
      'Log body weight': '体重を記録',
      'Weight history': '体重の履歴',
      'LATEST': '最新',
      'RECORDED CHANGE': '記録期間の変化',
      'BMI': 'BMI',
      'BMI history': 'BMIの履歴',
      'Based on your latest weight and height': '最新の体重と身長から算出',
      'Add your height in Body profile to calculate BMI.':
          'BMIの計算には身体プロフィールに身長を入力してください。',
      'BMI categories for adults do not apply under age 18.':
          '18歳未満には成人のBMI区分は適用されません。',
      'Based on your latest weight and height. BMI is a screening measure, not a diagnosis.':
          '最新の体重と身長から算出。BMIは目安であり、診断ではありません。',
      'Passphrase': 'パスフレーズ',
      'Nutrition estimates depend on the match, recipe, preparation and portion weight. Review food choices before saving.':
          '栄養価は食品の一致度、レシピ、調理方法、量によって異なります。保存前に内容を確認してください。',
      'What stays on this device and what is sent during search':
          '端末内に保存される情報と検索時に送信される情報',
      'Your food diary is stored in the app’s local SQLite database. Network access is used only when you search online food data.':
          '食事記録は端末内のデータベースに保存されます。ネットワークは食品データの検索時のみ使用します。',
      'Passphrase-encrypted file includes diary, goals, weight and photos':
          '食事、目標、体重、写真を含むパスワード暗号化ファイル',
      'Restores encrypted backups; legacy JSON is also supported':
          '暗号化バックアップを復元します。以前のJSON形式にも対応しています。',
      'Online searches send the search term to the chosen data provider. Do not enter sensitive information in a food search.':
          'オンライン検索では検索語が選択したデータ提供元に送信されます。検索に個人情報を入力しないでください。',
      'Profile & goal': 'プロフィールと目標',
      'Male': '男性',
      'Female': '女性',
      'Other / midpoint': 'その他 / 中間値',
      'Sedentary': '座りがちな生活',
      'Light activity': '軽い運動',
      'Moderate': '普通',
      'High': '高い',
      'Very high': '非常に高い',
      'Maintain weight': '体重を維持',
      'Gain weight / muscle': '体重・筋肉を増やす',
      'Lose weight': '体重を減らす',
      'Save profile': 'プロフィールを保存',
      'Choose the closest match': '最も近い食品を選択',
      'No matches. Try another name or enter nutrition below.':
          '一致する食品がありません。別の名前で検索するか、栄養価を入力してください。',
      'Take a photo': '写真を撮る',
      'Choose from gallery': '写真を選択',
      'Add the foods on your plate one by one. A photo is a reference; it cannot estimate ingredients or grams.':
          '皿の食品を一つずつ追加してください。写真は参考用で、食材や重量は推定できません。',
      'Filled from search, or edit manually': '検索結果から入力済み、または手動で編集',
      'Search online databases or enter your own values. Values below are per 100 g.':
          'オンラインデータベースを検索するか、値を入力してください。以下は100 gあたりです。',
      'NUTRI DIARY  •  EARLY PERSONAL BUILD  •  v0.1.0':
          '食誌 • 個人向け試作版 • v0.1.0',
      'A GENTLER WAY TO KEEP TRACK': 'やさしく続ける食事記録',
      'Set up your private diary': 'プライベートな食事日記を設定',
      'Replace local diary?': '端末内の日記を置き換えますか？',
      'Check age, height, weights and target date.': '年齢、身長、体重、目標日を確認してください。',
      'Estimates are intended for adults and are not medical advice. Muscle gain cannot be predicted from calories alone.':
          '推定値は成人向けで、医療上の助言ではありません。筋肉の増加はカロリーだけでは予測できません。',
      'Enter a food name, positive grams and valid non-negative nutrition values.':
          '食品名、正の重量、0以上の有効な栄養値を入力してください。',
      'Add each food, enter its grams, and check the nutrition values.':
          '食品ごとに重量を入力し、栄養値を確認してください。',
      'Could not save this meal. Please try again.':
          '食事を保存できませんでした。もう一度お試しください。',
      'At least one food has missing nutrients. Check its nutrition before relying on this total.':
          '栄養値が不足している食品があります。合計を参考にする前に確認してください。',
      'Log a food': '食事を記録',
      'Edit food': '食品を編集',
      'Plan a food': '食事を予定',
      'Food / dish name': '食品・料理名',
      'Amount eaten / planned': '食べた量・予定量',
      'Notes / preparation (optional)': 'メモ・調理方法（任意）',
      'Attach food photo (saved locally)': '写真を添付（端末内に保存）',
      'Protein': 'たんぱく質',
      'Carbs': '炭水化物',
      'Fat': '脂質',
      'Fiber': '食物繊維',
      'Sugar': '糖質',
      'Calories': 'カロリー',
      'Weight (kg)': '体重（kg）',
      'Note (optional)': 'メモ（任意）',
      'Age': '年齢',
      'Sex used for estimate': '推定に使う性別',
      'Height (cm)': '身長（cm）',
      'Current weight (kg)': '現在の体重（kg）',
      'Activity level': '活動レベル',
      'Goal': '目標',
      'Target weight (kg)': '目標体重（kg）',
      'Target date (YYYY-MM-DD)': '目標日（YYYY-MM-DD）',
      'Meal': '食事',
      'Food (e.g. cooked rice)': '食品（例：炊いたご飯）',
      'Amount': '量',
      'Meal notes (optional)': '食事メモ（任意）',
      'Calories / 100 g': 'カロリー / 100 g',
      'Protein / 100 g': 'たんぱく質 / 100 g',
      'Carbs / 100 g': '炭水化物 / 100 g',
      'Fat / 100 g': '脂質 / 100 g',
      'Fiber / 100 g': '食物繊維 / 100 g',
      'Sugar / 100 g': '糖質 / 100 g',
      'Nothing recorded for this day': 'この日の記録はありません',
      'Your diary starts here': '食事の記録を始めましょう',
      'Build a useful trend': '体重の傾向を記録しましょう',
      'Your data, your device.': 'あなたのデータはあなたの端末に',
      'A little progress, every meal.': '毎日の食事から、少しずつ。',
      'Today’s meals': '今日の食事',
      'Add a meal to see calories and macros build up through the day.':
          '食事を記録すると、1日のカロリーと栄養素を確認できます。',
      'Keep your diary useful, not perfect. Log the best estimate you have.':
          '完璧さより続けることが大切です。わかる範囲で記録しましょう。',
      'Decide before dinner.': '食べる前に計画しましょう。',
      'Add food you intend to eat. The forecast combines what you logged with what you plan.':
          '食べる予定の食品を追加できます。実績と予定から摂取量を予測します。',
      'Planned food': '食事の予定',
      'Nutrition per 100 g': '100 g あたりの栄養',
      'Measure trends, not single days.': '一日だけでなく、長期的な傾向を見ましょう。',
      'Body weight moves with hydration, salt, digestion and other normal variation. Focus on the trend over weeks.':
          '体重は水分や食事などで日々変動します。数週間単位の傾向を見ましょう。',
      'No readings yet': '記録はまだありません',
      'Add another reading': '次の体重を記録',
      'Across recorded range': '記録期間の変化',
      'Estimated daily target': '1日の目標（推定）',
      'Search rice, ramen, yogurt…': 'ご飯、ラーメン、ヨーグルトを検索…',
      'Encrypt backup': 'バックアップを暗号化',
      'Unlock backup': 'バックアップを開く',
      'Passphrase (12+ characters)': 'パスフレーズ（12文字以上）',
      'Repeat passphrase': 'パスフレーズを再入力',
      'Encrypt': '暗号化',
      'Open': '開く',
    },
    'zh': {
      'Home': '首页',
      'Calories over time': '热量变化',
      'A view of your logged food across the selected period.': '查看所选期间的饮食记录。',
      'Week': '周',
      'Month': '月',
      'Quarter': '季度',
      'Year': '年',
      'TOTAL': '总计',
      'DAILY AVERAGE': '日均',
      'In this period': '此期间',
      'Per day or month': '按日或月',
      'Logged calories': '已记录热量',
      'Your trend starts with a meal': '记录饮食，开始查看趋势',
      'Add food item': '添加食物',
      'Today': '今天',
      'Diary': '日记',
      'Plan': '计划',
      'Progress': '进度',
      'Settings': '设置',
      'Breakfast': '早餐',
      'Lunch': '午餐',
      'Dinner': '晚餐',
      'Snack': '加餐',
      'Log food': '记录饮食',
      'Add to this day': '添加到当天',
      'Search': '搜索',
      'Cancel': '取消',
      'Save': '保存',
      'Close': '关闭',
      'Continue': '继续',
      'Your name': '姓名',
      'Shown in the app header': '显示在应用标题栏',
      'Country / food reference': '国家 / 食品数据',
      'Language': '语言',
      'English': '英语',
      '日本語': '日语',
      '中文': '中文',
      '한국어': '韩语',
      'Color theme': '外观主题',
      'System': '跟随系统',
      'Light': '浅色',
      'Dark': '深色',
      'Following your device appearance': '跟随设备外观设置',
      'PERSONALIZATION': '个性化',
      'APPEARANCE': '外观',
      'PROFILE & GOAL': '个人资料与目标',
      'BACKUP & RESTORE': '备份与恢复',
      'PRIVACY': '隐私',
      'FOOD DATA & PRIVACY': '食品数据与隐私',
      'Body profile': '身体资料',
      'Weight goal': '体重目标',
      'Privacy policy': '隐私政策',
      'Export a backup': '导出备份',
      'Import a backup': '导入备份',
      'Log body weight': '记录体重',
      'Weight history': '体重历史',
      'LATEST': '最新',
      'RECORDED CHANGE': '记录变化',
      'BMI': 'BMI',
      'BMI history': 'BMI 历史',
      'Based on your latest weight and height': '根据最近的体重和身高计算',
      'Add your height in Body profile to calculate BMI.':
          '请在身体资料中填写身高以计算 BMI。',
      'BMI categories for adults do not apply under age 18.':
          '成人 BMI 分类不适用于 18 岁以下人群。',
      'Based on your latest weight and height. BMI is a screening measure, not a diagnosis.':
          '根据最近的体重和身高计算。BMI 仅供参考，不作诊断。',
      'Passphrase': '密码短语',
      'Nutrition estimates depend on the match, recipe, preparation and portion weight. Review food choices before saving.':
          '营养估算取决于匹配结果、食谱、烹饪方式和份量。保存前请检查食品信息。',
      'What stays on this device and what is sent during search':
          '哪些信息保存在设备上，哪些信息会在搜索时发送',
      'Your food diary is stored in the app’s local SQLite database. Network access is used only when you search online food data.':
          '饮食记录保存在设备本地数据库中。仅在线搜索食品数据时使用网络。',
      'Passphrase-encrypted file includes diary, goals, weight and photos':
          '密码加密文件包含饮食记录、目标、体重和照片',
      'Restores encrypted backups; legacy JSON is also supported':
          '可恢复加密备份，也支持旧版 JSON 文件',
      'Online searches send the search term to the chosen data provider. Do not enter sensitive information in a food search.':
          '在线搜索会将搜索词发送给所选数据提供方。请勿在食品搜索中输入敏感信息。',
      'Profile & goal': '个人资料与目标',
      'Male': '男性',
      'Female': '女性',
      'Other / midpoint': '其他 / 中间值',
      'Sedentary': '久坐',
      'Light activity': '轻度活动',
      'Moderate': '中等',
      'High': '高',
      'Very high': '非常高',
      'Maintain weight': '维持体重',
      'Gain weight / muscle': '增加体重 / 肌肉',
      'Lose weight': '减重',
      'Save profile': '保存资料',
      'No matches. Try another name or enter nutrition below.':
          '没有匹配结果。请尝试其他名称或在下方手动填写营养数据。',
      'Add the foods on your plate one by one. A photo is a reference; it cannot estimate ingredients or grams.':
          '请逐项添加餐盘中的食物。照片仅供参考，无法估算食材或重量。',
      'Filled from search, or edit manually': '已从搜索结果填写，也可手动修改',
      'Search online databases or enter your own values. Values below are per 100 g.':
          '搜索在线数据库或手动填写。以下数值均为每 100 克。',
      'NUTRI DIARY  •  EARLY PERSONAL BUILD  •  v0.1.0': '食誌 • 个人早期版本 • v0.1.0',
      'A GENTLER WAY TO KEEP TRACK': '轻松记录每一餐',
      'Set up your private diary': '设置你的私人饮食日记',
      'Replace local diary?': '要替换本地饮食记录吗？',
      'Check age, height, weights and target date.': '请检查年龄、身高、体重和目标日期。',
      'Estimates are intended for adults and are not medical advice. Muscle gain cannot be predicted from calories alone.':
          '估算仅供成年人参考，不构成医疗建议。仅凭热量无法预测肌肉增长。',
      'Enter a food name, positive grams and valid non-negative nutrition values.':
          '请填写食品名称、大于零的重量以及有效的非负营养数值。',
      'Add each food, enter its grams, and check the nutrition values.':
          '请添加每种食品，填写重量并检查营养数值。',
      'Could not save this meal. Please try again.': '无法保存这餐，请重试。',
      'At least one food has missing nutrients. Check its nutrition before relying on this total.':
          '至少有一种食品缺少营养数据。请先核对再参考总量。',
      'Log a food': '记录饮食',
      'Edit food': '编辑食品',
      'Plan a food': '计划饮食',
      'Food / dish name': '食品 / 菜名',
      'Amount eaten / planned': '食用 / 计划重量',
      'Notes / preparation (optional)': '备注 / 烹饪方式（可选）',
      'Attach food photo (saved locally)': '添加食物照片（保存在本地）',
      'Protein': '蛋白质',
      'Carbs': '碳水化合物',
      'Fat': '脂肪',
      'Fiber': '膳食纤维',
      'Sugar': '糖',
      'Calories': '热量',
      'Weight (kg)': '体重（kg）',
      'Note (optional)': '备注（可选）',
      'Age': '年龄',
      'Sex used for estimate': '用于估算的性别',
      'Height (cm)': '身高（cm）',
      'Current weight (kg)': '当前体重（kg）',
      'Activity level': '活动水平',
      'Goal': '目标',
      'Target weight (kg)': '目标体重（kg）',
      'Target date (YYYY-MM-DD)': '目标日期（YYYY-MM-DD）',
      'Meal': '餐次',
      'Food (e.g. cooked rice)': '食品（例如：熟米饭）',
      'Amount': '重量',
      'Meal notes (optional)': '餐食备注（可选）',
      'Calories / 100 g': '热量 / 100 克',
      'Protein / 100 g': '蛋白质 / 100 克',
      'Carbs / 100 g': '碳水化合物 / 100 克',
      'Fat / 100 g': '脂肪 / 100 克',
      'Fiber / 100 g': '膳食纤维 / 100 克',
      'Sugar / 100 g': '糖 / 100 克',
      'Nothing recorded for this day': '当天没有记录',
      'Your diary starts here': '开始记录你的饮食',
      'Build a useful trend': '记录体重变化趋势',
      'Choose the closest match': '选择最接近的食品',
      'Take a photo': '拍照',
      'Choose from gallery': '从相册选择',
      'Your data, your device.': '数据保存在你的设备上。',
      'A little progress, every meal.': '每一餐，进步一点点。',
      'Today’s meals': '今日饮食',
      'Add a meal to see calories and macros build up through the day.':
          '添加饮食记录，查看当天热量和营养素累计。',
      'Keep your diary useful, not perfect. Log the best estimate you have.':
          '记录贵在持续，不必追求完美。尽量填写准确估算。',
      'Decide before dinner.': '提前计划餐食。',
      'Add food you intend to eat. The forecast combines what you logged with what you plan.':
          '添加计划食用的食品，预测会合并已记录和计划内容。',
      'Planned food': '计划饮食',
      'Nutrition per 100 g': '每 100 克营养',
      'Measure trends, not single days.': '关注长期趋势，而非单日变化。',
      'Body weight moves with hydration, salt, digestion and other normal variation. Focus on the trend over weeks.':
          '体重会受水分、盐分和消化等影响而波动。请关注数周的趋势。',
      'No readings yet': '暂无记录',
      'Add another reading': '再记录一次',
      'Across recorded range': '记录期间的变化',
      'Search rice, ramen, yogurt…': '搜索米饭、拉面、酸奶…',
      'Encrypt backup': '加密备份',
      'Unlock backup': '解锁备份',
      'Passphrase (12+ characters)': '密码短语（至少 12 个字符）',
      'Repeat passphrase': '再次输入密码短语',
      'Encrypt': '加密',
      'Open': '打开',
    },
    'ko': {
      'Home': '홈',
      'Calories over time': '칼로리 변화',
      'A view of your logged food across the selected period.':
          '선택한 기간의 식사 기록을 보여 줍니다.',
      'Week': '주',
      'Month': '월',
      'Quarter': '분기',
      'Year': '년',
      'TOTAL': '합계',
      'DAILY AVERAGE': '일평균',
      'In this period': '이 기간',
      'Per day or month': '일 또는 월 기준',
      'Logged calories': '기록한 칼로리',
      'Your trend starts with a meal': '식사를 기록해 추세를 확인하세요',
      'Add food item': '음식 추가',
      'Today': '오늘',
      'Diary': '기록',
      'Plan': '계획',
      'Progress': '진행 상황',
      'Settings': '설정',
      'Breakfast': '아침',
      'Lunch': '점심',
      'Dinner': '저녁',
      'Snack': '간식',
      'Log food': '음식 기록',
      'Add to this day': '오늘에 추가',
      'Search': '검색',
      'Cancel': '취소',
      'Save': '저장',
      'Close': '닫기',
      'Continue': '계속',
      'Your name': '이름',
      'Shown in the app header': '앱 상단에 표시됩니다',
      'Country / food reference': '국가 / 식품 데이터',
      'Language': '언어',
      'English': '영어',
      '日本語': '일본어',
      '中文': '중국어',
      '한국어': '한국어',
      'Color theme': '테마',
      'System': '기기 설정',
      'Light': '라이트',
      'Dark': '다크',
      'Following your device appearance': '기기의 화면 설정을 따릅니다',
      'PERSONALIZATION': '개인 설정',
      'APPEARANCE': '화면',
      'PROFILE & GOAL': '프로필 및 목표',
      'BACKUP & RESTORE': '백업 및 복원',
      'PRIVACY': '개인정보',
      'FOOD DATA & PRIVACY': '식품 데이터 및 개인정보',
      'Body profile': '신체 프로필',
      'Weight goal': '체중 목표',
      'Privacy policy': '개인정보 처리방침',
      'Export a backup': '백업 내보내기',
      'Import a backup': '백업 가져오기',
      'Log body weight': '체중 기록',
      'Weight history': '체중 기록',
      'LATEST': '최근',
      'RECORDED CHANGE': '기록된 변화',
      'BMI': 'BMI',
      'BMI history': 'BMI 기록',
      'Based on your latest weight and height': '최근 체중과 키 기준',
      'Add your height in Body profile to calculate BMI.':
          'BMI를 계산하려면 신체 프로필에 키를 입력하세요.',
      'BMI categories for adults do not apply under age 18.':
          '성인 BMI 구간은 18세 미만에게 적용되지 않습니다.',
      'Based on your latest weight and height. BMI is a screening measure, not a diagnosis.':
          '최근 체중과 키 기준입니다. BMI는 참고 지표이며 진단이 아닙니다.',
      'Passphrase': '암호 문구',
      'Nutrition estimates depend on the match, recipe, preparation and portion weight. Review food choices before saving.':
          '영양 추정치는 음식 일치 결과, 레시피, 조리 방법 및 양에 따라 달라집니다. 저장 전에 확인하세요.',
      'What stays on this device and what is sent during search':
          '기기에 저장되는 정보와 검색 시 전송되는 정보',
      'Your food diary is stored in the app’s local SQLite database. Network access is used only when you search online food data.':
          '식사 기록은 기기의 로컬 데이터베이스에 저장됩니다. 온라인 음식 검색 시에만 네트워크를 사용합니다.',
      'Passphrase-encrypted file includes diary, goals, weight and photos':
          '식사 기록, 목표, 체중 및 사진을 포함한 암호화 파일',
      'Restores encrypted backups; legacy JSON is also supported':
          '암호화 백업을 복원하며 이전 JSON 파일도 지원합니다',
      'Online searches send the search term to the chosen data provider. Do not enter sensitive information in a food search.':
          '온라인 검색어는 선택한 데이터 제공업체로 전송됩니다. 검색에 민감한 정보를 입력하지 마세요.',
      'Profile & goal': '프로필 및 목표',
      'Male': '남성',
      'Female': '여성',
      'Other / midpoint': '기타 / 중간값',
      'Sedentary': '좌식 생활',
      'Light activity': '가벼운 활동',
      'Moderate': '보통',
      'High': '높음',
      'Very high': '매우 높음',
      'Maintain weight': '체중 유지',
      'Gain weight / muscle': '체중 / 근육 증가',
      'Lose weight': '체중 감량',
      'Save profile': '프로필 저장',
      'No matches. Try another name or enter nutrition below.':
          '일치하는 항목이 없습니다. 다른 이름으로 검색하거나 아래에 영양 정보를 입력하세요.',
      'Add the foods on your plate one by one. A photo is a reference; it cannot estimate ingredients or grams.':
          '접시의 음식을 하나씩 추가하세요. 사진은 참고용이며 재료나 중량을 추정하지 않습니다.',
      'Filled from search, or edit manually': '검색 결과로 입력했거나 직접 수정할 수 있습니다',
      'Search online databases or enter your own values. Values below are per 100 g.':
          '온라인 데이터베이스를 검색하거나 직접 입력하세요. 아래 값은 100 g 기준입니다.',
      'NUTRI DIARY  •  EARLY PERSONAL BUILD  •  v0.1.0':
          '食誌 • 초기 개인용 버전 • v0.1.0',
      'A GENTLER WAY TO KEEP TRACK': '부담 없이 식사 기록하기',
      'Set up your private diary': '나만의 식사 일기 설정',
      'Replace local diary?': '기존 식사 기록을 바꿀까요?',
      'Check age, height, weights and target date.':
          '나이, 키, 체중 및 목표 날짜를 확인하세요.',
      'Estimates are intended for adults and are not medical advice. Muscle gain cannot be predicted from calories alone.':
          '추정치는 성인용이며 의료 조언이 아닙니다. 칼로리만으로 근육 증가를 예측할 수 없습니다.',
      'Enter a food name, positive grams and valid non-negative nutrition values.':
          '음식 이름, 0보다 큰 중량 및 유효한 0 이상의 영양 값을 입력하세요.',
      'Add each food, enter its grams, and check the nutrition values.':
          '음식을 추가하고 중량과 영양 값을 확인하세요.',
      'Could not save this meal. Please try again.':
          '식사를 저장하지 못했습니다. 다시 시도하세요.',
      'At least one food has missing nutrients. Check its nutrition before relying on this total.':
          '영양 정보가 없는 음식이 있습니다. 합계를 참고하기 전에 확인하세요.',
      'Log a food': '음식 기록',
      'Edit food': '음식 수정',
      'Plan a food': '식사 계획',
      'Food / dish name': '음식 이름',
      'Amount eaten / planned': '섭취 / 예정량',
      'Notes / preparation (optional)': '메모 / 조리법 (선택)',
      'Attach food photo (saved locally)': '음식 사진 첨부 (기기에 저장)',
      'Protein': '단백질',
      'Carbs': '탄수화물',
      'Fat': '지방',
      'Fiber': '식이섬유',
      'Sugar': '당류',
      'Calories': '칼로리',
      'Weight (kg)': '체중 (kg)',
      'Note (optional)': '메모 (선택)',
      'Age': '나이',
      'Sex used for estimate': '계산에 사용할 성별',
      'Height (cm)': '키 (cm)',
      'Current weight (kg)': '현재 체중 (kg)',
      'Activity level': '활동 수준',
      'Goal': '목표',
      'Target weight (kg)': '목표 체중 (kg)',
      'Target date (YYYY-MM-DD)': '목표 날짜 (YYYY-MM-DD)',
      'Meal': '식사',
      'Food (e.g. cooked rice)': '음식 (예: 지은 밥)',
      'Amount': '양',
      'Meal notes (optional)': '식사 메모 (선택)',
      'Calories / 100 g': '열량 / 100 g',
      'Protein / 100 g': '단백질 / 100 g',
      'Carbs / 100 g': '탄수화물 / 100 g',
      'Fat / 100 g': '지방 / 100 g',
      'Fiber / 100 g': '식이섬유 / 100 g',
      'Sugar / 100 g': '당류 / 100 g',
      'Nothing recorded for this day': '오늘 기록이 없습니다',
      'Your diary starts here': '식사 기록을 시작하세요',
      'Build a useful trend': '체중 추이를 기록하세요',
      'Choose the closest match': '가장 가까운 음식을 선택하세요',
      'Take a photo': '사진 촬영',
      'Choose from gallery': '갤러리에서 선택',
      'Your data, your device.': '내 데이터는 내 기기에.',
      'A little progress, every meal.': '매 끼니마다 조금씩 나아가요.',
      'Today’s meals': '오늘의 식사',
      'Add a meal to see calories and macros build up through the day.':
          '식사를 기록하고 하루 열량과 영양소를 확인하세요.',
      'Keep your diary useful, not perfect. Log the best estimate you have.':
          '완벽함보다 꾸준한 기록이 중요합니다. 가능한 정확히 기록하세요.',
      'Decide before dinner.': '미리 식사를 계획하세요.',
      'Add food you intend to eat. The forecast combines what you logged with what you plan.':
          '먹을 음식을 추가하면 기록과 계획을 합쳐 예상 섭취량을 보여줍니다.',
      'Planned food': '식사 계획',
      'Nutrition per 100 g': '100 g당 영양 정보',
      'Measure trends, not single days.': '하루보다 장기적인 추세를 확인하세요.',
      'Body weight moves with hydration, salt, digestion and other normal variation. Focus on the trend over weeks.':
          '체중은 수분, 염분, 소화 등으로 매일 변합니다. 몇 주간의 추세를 확인하세요.',
      'No readings yet': '기록이 없습니다',
      'Add another reading': '다음 체중을 기록하세요',
      'Across recorded range': '기록 기간의 변화',
      'Search rice, ramen, yogurt…': '밥, 라면, 요거트 검색…',
      'Encrypt backup': '백업 암호화',
      'Unlock backup': '백업 잠금 해제',
      'Passphrase (12+ characters)': '암호 문구 (12자 이상)',
      'Repeat passphrase': '암호 문구 다시 입력',
      'Encrypt': '암호화',
      'Open': '열기',
    },
  };

  static String translate(String value, String languageCode) =>
      _strings[languageCode]?[value] ?? value;

  @override
  Widget build(BuildContext context) {
    final translated = translate(
      data,
      Localizations.localeOf(context).languageCode,
    );
    return Text(
      translated,
      style: style,
      strutStyle: strutStyle,
      textAlign: textAlign,
      textDirection: textDirection,
      locale: locale,
      softWrap: softWrap,
      overflow: overflow,
      maxLines: maxLines,
      semanticsLabel: semanticsLabel,
      textWidthBasis: textWidthBasis,
      textHeightBehavior: textHeightBehavior,
      selectionColor: selectionColor,
    );
  }
}
